# Generated by Django 4.0.1 on 2022-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
